### ISSUE TITLE
Markdown - Lists 3 or more levels deep do not render correctly

### ISSUE THREAD

**Issue by poteto** [emberjs/cfp-app#42]
Markdown lists nested 3 levels deep (or more) are flattened into a maximum of two levels. Probably an issue with redcarpet - https://github.com/vmg/redcarpet/issues/254

**Comment by wifelette** [comment]
![2015-09-16_16-05-56](https://cloud.githubusercontent.com/assets/25433/9920897/0427ccf0-5c8d-11e5-8389-e1c147fd4c58.png)

Verified, still an issue, screenshot attached.

**Comment by brandonjmckay** [comment]
Still an issue with the latest redcarpet gem, not sure if there's an alternative that can help us here.

**Comment by brandonjmckay** [comment]
https://github.com/vmg/redcarpet/issues/115#issuecomment-4187069

**Comment by brandonjmckay** [comment]
The line they point to is here, https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/markdown.h#L129 not sure how to override this for us though.

**Comment by wifelette** [comment]
@brandonjmckay Can you look into replacing redcarpet with [CommonMarker](https://github.com/gjtorikian/commonmarker)? Might be the solution :)

(Or some other common mark implementation?)
