### ISSUE TITLE
Reorganize display of fields on proposal submission page

### ISSUE THREAD

**Issue by wifelette** [emberjs/cfp-app#56]
Specifically, the delineation ought be 1) fields reviewers can see in the blind phase and 2) fields they cannot. Right now they're mixed. Ideal is that you first fill out your bio info, so the stuff reviewers _can't_ see in the blind phase, and _then_ you fill out your actual proposal—the stuff the blind reviewers see.

In a perfect world, this would be paginated on to two pages, and if you filled out page 1 but not 2, it would be saved as a Draft. But that might be a bunch more work, unsure :p 

#### Section 1, Not Visible During Blind Phase:

* Are there recordings of you giving talks online
* Where do you live
* Headshot
* Bio
* Website, blog, etc.
* GitHub username
* Twitter username
* Link to a Video Pitch

#### Section 2, Visible During Blind Phase:

* Is this a new talk?
* Title
* Abstract
* Details
* Pitch

There's extra copy and titles and whatnot that we might be able to lose once we do this. 

There's also a spot that shows the user their Gravatar. We can lose this altogether.

**Comment by chancancode** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by chancancode** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by chancancode** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by chancancode** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
