### ISSUE TITLE
Invitation emails aren't sending

### ISSUE THREAD

**Issue by wifelette** [emberjs/cfp-app#70]
@brandonjmckay is there perhaps more setup required for emails? I haven't tested the acceptance/rejection email stuff yet.

**Comment by brandonjmckay** [comment]
Not sure, are you saying that an email _did not_ go out when you expected it to?

Or is this just a question of whether there needs some setup for it?

**Comment by brandonjmckay** [comment]
I didn't touch the existing mail integration, so if it worked before I expect it to continue working.
But I'll address it if it is broken.

**Comment by wifelette** [comment]
Ran more tests, confirmed. Can you poke around and see what you come up with?
